services:
  - type: web
    name: petcare-backend
    env: node
    rootDir: backend
    buildCommand: npm run render-build
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petcare-db
          property: connectionString
      - key: DATABASE_SSL
        value: true
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: petcare-db
    plan: free